[project]
name = "segunda-prueba"
version = "0.1.0"
description = ""
authors = [
    {name = "Your Name",email = "you@example.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "python-dotenv (>=1.2.3,<2.0.0)",
    "pandas (>=3.0.6,<4.0.0)",
    "numpy (>=2.5.3,<3.0.0)",
    "scikit-learn (>=1.9.1,<2.0.0)",
    "mlflow (>=3.16.1,<4.0.0)",
    "fastapi (>=0.141.1,<0.142.0)",
    "uvicorn (>=0.53.0,<0.54.0)",
    "prometheus-fastapi-instrumentator (>=8.1.0,<9.0.0)",
    "notebook (>=7.6.3,<8.0.0)",
    "matplotlib (>=3.11.2,<4.0.0)",
    "seaborn (>=0.13.2,<0.14.0)",
    "xgboost (>=3.4.1,<4.0.0)"
]

[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
