# Etapa 1: Constructor
FROM python:3.12-slim AS builder

WORKDIR /app

RUN pip install --no-cache-dir "poetry>=2.0.0"

COPY pyproject.toml poetry.lock* ./

RUN poetry config virtualenvs.create false \
    && poetry install --no-root --only main

# Etapa 2: Imagen Final
FROM python:3.12-slim

WORKDIR /app

COPY --from=builder /usr/local/lib/python3.12/site-packages /usr/local/lib/python3.12/site-packages
COPY --from=builder /usr/local/bin /usr/local/bin

COPY src/ ./src

# Exponer el puerto nativo de Streamlit
EXPOSE 8501

# Comando para arrancar Streamlit
CMD ["streamlit", "run", "src/app/app.py", "--server.port=8501", "--server.address=0.0.0.0"]
